spring.application.name=hotelManagementsystem-AIRBNB

#DB configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb_vl
spring.datasource.username=postgres
spring.datasource.password=eighteenlpa
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#this will only let the api with path  /api/v1 hit the controller
server.servlet.context-path=/api/v1




