spring.application.name=hotelManagementsystem-AIRBNB

#DB configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb_vl
spring.datasource.username=postgres
spring.datasource.password=eighteenlpa
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#this will only let the api with path  /api/v1 hit the controller
server.servlet.context-path=/api/v1

#jwt security key
jwt.secretKey=ijfhuwe8yv78y84ybveybudyveih8932y8vbdizdie9hn7yn49ng
#api key for holiday api
apiKey=a0x8z93O83XfoVYbSY9PhN3xvtOLV9Id

#actuator configurations

management.endpoints.web.exposure.include=health,info
info.app.name=BookMyStay
info.app.version=1.0.0
info.app.author=TUSHAR TYAGI

management.info.java.enabled=true
management.info.os.enabled=true
#management.info.git.mode=simple

#swagger api configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


frontend.url=http://localhost:8080

stripe.secret.key=sk_test_51SsiGbHFPkHG0GaUSig4JJbI5XGi9SwxhvErrbVbplC8mPLj48fQh1YZ3JxLBDcHAdsQwKdyRVyBuGtvbjSdDGpK000Mhmgh86

stripe.webhook.secret=whsec_500d8c04f785ad059ad75b85476f3e86f33e7dc8b7492a47817b2ff940213d9a
