spring.application.name=hotelManagementsystem-AIRBNB


#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



#this will only let the api with path  /api/v1 hit the controller
server.servlet.context-path=/api/v1

#jwt security key
jwt.secretKey=${JWT_SECRETKEY}

#api key for holiday api
apiKey=${H_APIKEY}

#actuator configurations

management.endpoints.web.exposure.include=health,info
info.app.name=BookMyStay
info.app.version=1.0.0
info.app.author=TUSHAR TYAGI

management.info.java.enabled=true
management.info.os.enabled=true
#management.info.git.mode=simple

#swagger api configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


frontend.url=http://localhost:8080

stripe.secret.key=${S_APIKEY}

stripe.webhook.secret=${sWebhook_SecretKey}
