#Rds configurations
spring.datasource.url=jdbc:postgresql://bookmystay-postgress.c90cmou0w7sm.eu-north-1.rds.amazonaws.com:5432/airBnb_vl
spring.datasource.username=root
spring.datasource.password=Eighteen18lpa
