version: "3.9"

services:

  server:
    image: bookmystay:latest
    container_name: bookmystay-server
    restart: unless-stopped
    env_file:
      - server/prod.env
    ports:
      - "8080:8080"


